import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

// SQLite (Cloudflare D1) schema, generated by `pnpm db:generate` into ./drizzle.
// Column shapes mirror the legacy Supabase/Postgres schema 1:1 so existing data
// (migrated via a one-time export/import, see README) keeps rendering with no
// changes to lib/media.ts / lib/members.ts. See AGENTS.md §5.

const bool = (name: string) => integer(name, { mode: "boolean" });

// Lookup tables: year, semester, course, tech, industry — same {id, name} shape.
function lookupTable(name: string) {
  return sqliteTable(name, {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
  });
}

export const year = lookupTable("year");
export const semester = lookupTable("semester");
export const course = lookupTable("course");
export const tech = lookupTable("tech");
export const industry = lookupTable("industry");

export const project = sqliteTable("project", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  projectUUID: text("projectUUID").notNull().unique(),
  name: text("name").notNull(),
  slogan: text("slogan"),
  projectDescription: text("projectDescription"),
  targetAudience: text("targetAudience"),
  productDescription: text("productDescription"),
  projectViability: text("projectViability"),
  link: text("link"),
  year: integer("year").references(() => year.id),
  semester: integer("semester").references(() => semester.id),
  course: integer("course").references(() => course.id),
  tech: integer("tech").references(() => tech.id),
  industry: integer("industry").references(() => industry.id),
  // JSON string: {"path": string[]} — see lib/media.ts.
  logoImg: text("logoImg"),
  teamImg: text("teamImg"),
  productImg: text("productImg"),
  date: text("date")
    .notNull()
    .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  status: bool("status").notNull().default(false),
});

export const member = sqliteTable("member", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  projectUUID: text("projectUUID").notNull(),
  // JSON string of the members' names (array). See lib/members.ts.
  name: text("name"),
  contact: text("contact"),
  isFounder: bool("isFounder"),
  isLeader: bool("isLeader").notNull().default(false),
});

// ---------------------------------------------------------------------------
// Admin auth (replaces Supabase Auth + the `admins` allowlist table). Every
// row here is an admin — see lib/auth/*. Password hashing: PBKDF2-SHA256 via
// Web Crypto (available in the Workers runtime, no native deps).
// ---------------------------------------------------------------------------

export const adminUser = sqliteTable("adminUser", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  passwordHash: text("passwordHash").notNull(),
  name: text("name"),
  createdAt: integer("createdAt", { mode: "timestamp_ms" })
    .notNull()
    .default(sql`(unixepoch('subsec') * 1000)`),
});

export const adminSession = sqliteTable("adminSession", {
  id: text("id").primaryKey(),
  adminUserId: text("adminUserId")
    .notNull()
    .references(() => adminUser.id, { onDelete: "cascade" }),
  expiresAt: integer("expiresAt", { mode: "timestamp_ms" }).notNull(),
  createdAt: integer("createdAt", { mode: "timestamp_ms" })
    .notNull()
    .default(sql`(unixepoch('subsec') * 1000)`),
});

export const loginAttempt = sqliteTable("loginAttempt", {
  adminUserId: text("adminUserId")
    .primaryKey()
    .references(() => adminUser.id, { onDelete: "cascade" }),
  failures: integer("failures").notNull(),
  windowStart: integer("windowStart", { mode: "timestamp_ms" }).notNull(),
});
